# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Boatell-v3' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Boatell-v3

  pod 'JTAppleCalendar'
  pod 'Firebase/Analytics'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'Firebase/Messaging'
  pod 'Stripe'
  pod ‘Firebase/Functions’

end
